version: '3.8'  # 使用 Docker Compose 版本 3.8

services:
  backend:  # 服務名稱，可自訂
    build:
      context: .  # 建置映像使用當前資料夾
      dockerfile: Dockerfile.dev  # 使用開發用的 Dockerfile
    container_name: my-backend  # 指定容器名稱
    ports:
      - "3000:3000"  # 將本機的 3000 埠對應到容器的 3000 埠
    volumes:
      - .:/app  # 將當前專案資料夾掛載到容器內，程式碼變動能即時反應
      - /app/node_modules  # 確保 node_modules 使用容器內部的，不會被主機覆蓋
    env_file:
      - .env  # 讀取 .env 檔案載入環境變數
    restart: unless-stopped  # 自動重啟容器（除非你手動停止）
